apiVersion: kind.x-k8s.io/v1alpha4
kind: Pod
metadata:
  name: nginx_giropops
  labels:
    name: nginx_giropops
spec:
  containers:
  - name: nginx_giropops
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
