apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dep-nginx
  name: dep-nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: dep-nginx
    spec:
      containers:
      - name: dep-nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 80
          #httpGet: 
          #  path: /
          #  port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
