apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dep-nginx
  name: dep-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: dep-nginx
    spec:
      containers:
      - name: dep-nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
