apiVersion: v1
kind: Pod
metadata:
  name: nginx-giropops
  labels:
    name: nginx-giropops
    run: nginx-giropops
    app: giropops-strigus
spec:
  containers:
  - name: nginx-giropops
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
dnsPolicy: ClusterFirst
restartPolicy: Always
