apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "my-pod"
  name: "my-pod"
spec:
  containers:
  - image: nginx
    name: mynginx
    volumeMounts:
    - mountPath: /my1path
      name: "my-emptydir"
    resources:
      limits:
        cpu: "1"
        memory: "64Mi"
      requests:
        cpu: "0.5"
        memory: "32Mi"
  - image: alpine
    name: myalpine
    args:
    - sleep
    - "1000"
    volumeMounts:
    - mountPath: /my2path
      name: "my-emptydir"
    resources:
      limits:
        cpu: "1"
        memory: "64Mi"
      requests:
        cpu: "0.5"
        memory: "32Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: "my-emptydir"
    emptyDir:
      sizeLimit: "128Mi"
status: {}
