apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: girus
  namespace: dev
spec:
  containers:
  - image: ubuntu
    name: ubuntu-container
    args:
    - sleep
    - "1000"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
