apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: nginx 
    name: nginx-container
    resources: {}
  - image: alpine
    name: alpine-container
    args:
    - sleep
    - "500" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
