apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: girus
  namespace: dev
spec:
  containers:
  - image: nginx
    name: nginx-container
    resources:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
